AWSTemplateFormatVersion: 2010-09-09
Description: ---
Resources: 
  rdsdbinsatnce:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 10
      AllowMajorVersionUpgrade: false  
      AvailabilityZone: ap-south-1a
      DBInstanceClass: db.t2.micro
      DBName: mydb
      DeleteAutomatedBackups: false  
      DeletionProtection: false  
      Engine: MySQL
      EngineVersion: "5.7.22"
      MasterUsername: mydb  
      MasterUserPassword: premsai007
      MultiAZ: false 
      Port: 3306
      PubliclyAccessible: true  
      VPCSecurityGroups: 
        - sg-1168cd7f
